# Generated by Django 5.0.1 on 2024-01-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rc_book',
            field=models.FileField(default='', upload_to='pdfs'),
        ),
    ]
