# Generated by Django 5.0.1 on 2024-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vehicle_rc_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('COD', 'COD')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('COD', 'COD')], default='', max_length=255),
        ),
    ]
