# Generated by Django 5.0.1 on 2024-01-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_payment_mode_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Offline', 'Offline')], default='', max_length=255),
        ),
    ]
