# Generated by Django 5.0.1 on 2024-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_booking_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='', max_length=255),
        ),
    ]
