# Generated by Django 5.0.1 on 2024-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_amount',
            field=models.IntegerField(default=0),
        ),
    ]
