# Generated by Django 5.0.1 on 2024-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_status',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
