# Generated by Django 5.0.3 on 2024-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='usertype',
            field=models.CharField(choices=[('Vehicle Owner', 'Vehicle Owner'), ('Vehicle Renter', 'Vehicle Renter')], max_length=100),
        ),
    ]
